### ISSUE TITLE
Where is source code hosted?

### ISSUE THREAD

**Issue by iskrisis** [Fred89/flatboard#10]
Hello i am confused there is no sourcecode in the repo. Why is that? Is there a way to contribute?

**Comment by Fred89** [comment]
The script is a forum, it remains the best support means;)

**Comment by KaKi87** [comment]
Hello,

This does not answer the question.

According to the repository license, and file headers, the code is released under the MIT license, which means, it should be easy to contribute to.

Thanks

**Comment by arran-nz** [comment]
Not sure why this is closed, cannot find the source anywhere
