### ISSUE TITLE
Please remove the Psuedo login!!

### ISSUE THREAD

**Issue by CookieGuy123** [Fred89/flatboard#11]
**Please remove it!**
it's easy for spammers to create new accounts and spam alot
A register feature would be better.
:)

_IN FACT.. on YOUR forum there is a spammer right now_
They are spamming things like 'a' 'b' 'c' 'd' etc
https://flatboard.org/view.php/forum/announcements
https://flatboard.org/view.php/forum/general-questions
And I think it's the same person.. with different accounts.

**Comment by Fred89** [comment]
Hi @CookieGuy123,
This is not SPAM but FLOOD (same user)!
Do you know about multi-user accounts?
The problem will be the same with user accounts, why bother managing members in a Flat-files system in this case?
In the case of FLOOD on the Flatboard site, I could have banned the user for the next flood ...

**Comment by CookieGuy123** [comment]
Ok..
