### ISSUE TITLE
Unpacker redirects to 404 page.

### ISSUE THREAD

**Issue by CookieGuy123** [Fred89/flatboard#12]
I am using Flatboard 3.0
The installer unpacked the files then went to a 404 page. I have to go to the URL again to get the installer.
I have a video attached.
(I think there's a typo in the code for the unpacker)

https://drive.google.com/file/d/18FVYC5duCPObHIxB4mqP_c6mT-YkX2fC/view

**Comment by Fred89** [comment]
I fixed this bug on Flatboard 3.0.1, thx for repport ;)
