### ISSUE TITLE
About the Chinese version of this project

### ISSUE THREAD

**Issue by arleycn** [Fred89/flatboard#14]
I have added the Chinese version of this project, please add it to your project in the next update if you can, thanks!
<a href="https://github.com/arleycn/Flatboard_Chinese " target="_blank"><strong>Flatboard_Chinese</strong></a>

**Comment by Fred89** [comment]
@arleycn Thank you for your participation, I will add it in the next version!

**Comment by arleycn** [comment]
Okay, this is just the initial test version, I will fix him in time if there are problems, thanks!
