### ISSUE TITLE
Installer Fails on PHP8

### ISSUE THREAD

**Issue by teamayu** [Fred89/flatboard#15]
Fatal error: Uncaught ValueError: Path cannot be empty in \lib\Asset.lib.php on line 74

Thanks.

**Comment by surveybuilder-admin** [comment]
Thanks for the feedback, sorry for the very late response, honestly, it might have to do with the file that it's looking for is empty, and PHP8 is very strict on empty folders, unlike PHP5.3+ it's not, will try to fix it at soon as possible for PHP8, when it's tested out.

Thank you,
SurveyBuilder-Admin
