### ISSUE TITLE
Startseite des Forums wird nicht verlinkt - Flatboard aktuelle Version

### ISSUE THREAD

**Issue by AlexL777** [Fred89/flatboard#2]
Hallo Fred, 
hoffe, dass man hier auf Deutsch schreiben kann. Ich habe durch einen Tipp im Bludit Support Forum dein Flatboard entdeckt und habe es gleich installiert. Ich will es gerne einsetzen und bräuchte deine Hilfestellung.

Es ist so, dass die Installation sehr einfach war, aber die Forum-Startseite, wenn ich auf das Textlogo im Frontend klicke, nicht verlinkt wird. 

Muss ich noch etwas an der .htaccess schrauben oder ist es noch ein Bug?

Freue mich über deine Hilfestellung und viele Dank. Flatboard macht schon mal guten ersten Eindruck :smile:

**Comment by AlexL777** [comment]
Coole Sache, vielen Dank. Ich habe die .htaccess mit diesem Inhalt erstellt und schon geht wieder alles :)

    RewriteEngine on
    RewriteBase /cms/flatboard/

Habe nur so geahnt, dass es so klappen könnte und sieh da, funktioniert tatsächlich.

**Comment by Fred89** [comment]
Vielen Dank für Ihre Rück, 
Flachbrett braucht normalerweise nicht in .htaccess, aber dies sollte auf dem Server ab ...

**Comment by Fred89** [comment]
Der Versuch, die Wurzel des Anrufs in der install.php Datei header.php ändern
```php
if (!defined('PATH_ROOT')) define('PATH_ROOT',  __DIR__.DS);
```
oder
```php
if (!defined('PATH_ROOT')) define('PATH_ROOT',  './');
```

**Comment by AlexL777** [comment]
Happy because of the feedback. I've still done an installation and also in the subdirectory. It worked without .htaccess. 

Probably had something to do with my server.

But Thanks for the advice and now I collect time experience with the flatboard.

**Comment by Fred89** [comment]
No problem, i close this issue ;)
