### ISSUE TITLE
I see no content in the topics of my FlatBoard Forums - why is it

### ISSUE THREAD

**Issue by AlexL777** [Fred89/flatboard#3]
Hello Developers,

I have with my flat board a problem and although I can not see any content in the Forum Topic. I have just the last Flat Board Version installed and at this URL http://internetblogger.org/flatboard/view.php/topic/2016-01-300005597faad it sees no content.

But when changing the topic, in Markdown editor is already more content. I do not know where it comes from and what it could be.

Here again a screenshot.

Whether you give me maybe can help?

Thank you in advance.

![flatboard-error-in-topic](https://cloud.githubusercontent.com/assets/7885632/12691882/a4776ff8-c6f0-11e5-8bc2-4dc9bbc7ace1.png)

**Comment by Fred89** [comment]
Hello,
There have no FlatBoard installed to this url ...
Thank you to reinstall the forum by enabling debugging. To do this edit the init.php file, replacing 'DEBUG_MODE' FALSE 'DEBUG_MODE' TRUE

Write me the notices/errors here please.

**Comment by AlexL777** [comment]
So in debug mode shows no errors and my Firefox Inspector displays in the Console to the.

    SimpleMDE: Error. No element found what.

Whether it has something to do with this plugin, I can not tell you. Elsewhere I have two flat board installations and there I do not have this problem.

I Do not know why at once.

**Comment by AlexL777** [comment]
Now I have found the error. The plugin SimpleMDE is not compatible with PHP 7.0.

I have now set back to PHP 5.6 back and it all works again. So you can see that, PHP 7.0 again.

I've just tried and lo, in fact it was the PHP version.

**Comment by Fred89** [comment]
Yeah, and Parsdown (Flatboard use this lib for markdown) is not compatible to with php 7, I think it is still too early to put php 7 on its server.

**Comment by AlexL777** [comment]
OK, then I know now about it. I wanted the GRAV CMS run under PHP 7.0, which worked first time. But it will take quite a while, rather all open source software and tools with PHP 7.0 will work.

With PHP 5.6, but it is also, while you can leave it at the first time I think.

At least we have found the mistake and I wanted to give up.

**Comment by Fred89** [comment]
I advise you to wait more feedbacks on php7 before activating.
Never give up, you were right to ask me questions and does not hesitate to ask if you have other problems with Flatboard ;)

**Comment by AlexL777** [comment]
Yes, I am running not even WordPress already with PHP 7.0. As I wait really quite a while.

Thank you and if I should have more question and problems with Flatboard, then I like to turn to you.

**Comment by Fred89** [comment]
No problem :smirk:
