### ISSUE TITLE
Problem with flatboard and windows

### ISSUE THREAD

**Issue by nickbe** [Fred89/flatboard#4]
Currently flatboard has its problems under windows.
paths to css files cannot be found.

Tested with Apache/PHP 5.x

**Comment by Fred89** [comment]
Sorry I was away for a week, I look at it next week;)

**Comment by Fred89** [comment]
Do you have a oline demo installation please?

**Comment by Fred89** [comment]
Please can it confirm that the latest version of flatboard work?

**Comment by nickbe** [comment]
I'll try the latest version after the weekend when I'm back in my office.

**Comment by nickbe** [comment]
Still doesn't work. 
There's still a problem with windows paths and backslahes

**Comment by Fred89** [comment]
Please try the [version 0.8 Beta](http://flatboard.free.fr/download.php).Thanks!

**Comment by nickbe** [comment]
Latest version works. Finally :)

**Comment by nickbe** [comment]
Current version again does not work with windows.
