### ISSUE TITLE
Flatboard 0.7.7 code output with Markdown does not work

### ISSUE THREAD

**Issue by AlexL777** [Fred89/flatboard#5]
Hello Developers,

I have a problem with Flatboard 0.7.7 Beta namely works for me PHP code or general code output, when I work with Markdown in my forum.

Since I wanted to use Markdown in this forum post and embed PHP code, but there is no frame around the code and no code box appears.

Look at you out this forum post: http://flarum.biz/view.php/topic/2016-03-2509534861300

How can it be, or am I doing something wrong?

Thanks in advance.

**Comment by Fred89** [comment]
Hi Alex,

Put your code between [code] [/ code] to be it considered.
All markdown format is not taken into account for security reasons, as anonymous can répondres there any time and incorporate malicious content.

I reflected to integrate other content editor in a future version of Flatboard.
Ps: i have reply in your forum, delete it ;)

**Comment by Fred89** [comment]
In simpleMDE plugin config changes toolbar buttons with this:
```
"bold", "italic", "heading", "|", "link", "image", "code", "horizontal-rule", "|", "preview", "side-by-side", "|", "undo", "redo", "|", "fullscreen", "guide"
```

**Comment by AlexL777** [comment]
Thank you, it has so worked. Then I now know and can work with [code].
Since I am looking forward to the future editor :smile:
