### ISSUE TITLE
Flatboard Search is not working

### ISSUE THREAD

**Issue by AlexL777** [Fred89/flatboard#6]
Hello dear developers,

I now noticed in my flatboard under http://flarum.biz that the internal search does not work. Search times with me for a topic such as "cms" in the search.

It will not display the search results, which have to be.

Moreover, when I click on one of the search results, behind it is a 404 Error.

Can you even comprehend it with you?

Looking forward, if you can help me.

Thanks in advance.

**Comment by Fred89** [comment]
Hi Alex, 
try this file please => http://flatboard.free.fr/search.txt
Just rename to search.php

**Comment by AlexL777** [comment]
Hi,

ok, great, was successful and my Forum Search now works. Thank you again!

**Comment by Fred89** [comment]
Thank you for your feeback ;)
